---
title: "STAT4026Consultation3Q2"
author: '500199066'
date: "2024-05-13"
output: html_document
---

```{r}
library(readxl)
library(tidyverse)
library("survival")
library("survminer")
data = readxl::read_xlsx("240508_Survival_project_for_maths_students_opened.xlsx")
```

```{r}
# data$`Sex (Male 1, Female 2)` = as.factor(data$`Sex (Male 1, Female 2)`)
data[data == 999.0] <- NA
data = data %>% filter(!Diagnosis_number == 2.5)
data$Diagnosis_number = as.factor(data$Diagnosis_number)
data$`CBI::PercentSleepFCorrected` = as.numeric(data$`CBI::PercentSleepFCorrected`)
data$`CBI::PercentBeliefsFCorrected` = as.numeric(data$`CBI::PercentBeliefsFCorrected`)
```

```{r}
#Non numeric variables
non_numeric_vars <- names(data)[!sapply(data, is.numeric)]
#Delete non numeric variables
df <- data %>% select(-'PID', -'Diagnosis_number', -`Onset till death`, -`Original_order`, -'SummaryPrimaryDiagnosis_descriptor', -`DAD::ExportTotalIadls`,	-`DAD::ExportTotalDad`,	-`DAD::ExportTotalBadl`)
#Standarize data
data_standardized <- as.data.frame(lapply(df, rescale), check.names = FALSE)
```

```{r}
#Combine non numeric variables
data_stand <- cbind(data$Diagnosis_number, data_standardized)

colnames(data_stand)[colnames(data_stand) == "data$Diagnosis_number"] <- "Diagnosis_number"
colnames(data_stand)[colnames(data_stand) == "data$`Sex (Male 1, Female 2)`"] <- "Sex (Male 1, Female 2)"
data_stand$`Sex (Male 1, Female 2)` = as.factor(data_stand$`Sex (Male 1, Female 2)`)
# colnames(data_stand)[colnames(data_stand) == "data$`CBI::PercentBeliefsFCorrected`"] <- "CBI::PercentBeliefsFCorrected"
# colnames(data_stand)[colnames(data_stand) == "data$`CBI::PercentSleepFCorrected`"] <- "CBI::PercentSleepFCorrected"
```

```{r}
library(survival)
library(rms)  # one possible source for a `vif`-function .... there are many
data_stand_no_high_vif = data_stand %>% select(-c(`ACEIII::ACEIIITotal`))
fit <- coxph(Surv(`Diagnosis till death`) ~., data= data_stand_no_high_vif)
fit
vif <- rms::vif(fit)
vif
```


```{r}
#Model
m <- coxph(Surv(`Diagnosis till death`) ~ strata(data$Diagnosis_number) + `Age at diagnosis` + `Sex (Male 1, Female 2)` + `Disease duration at diagnosis` + `ACEIII::ACEIIITotal`, data = data_stand, model = TRUE)


data_stand <- na.omit(data_stand)
data_stand$`Diagnosis till death` <- as.numeric(data_stand$`Diagnosis till death`)
numeric_columns <- sapply(data_stand, is.numeric)
data_stand[numeric_columns] <- scale(data_stand[numeric_columns])
library(car)
linear_model <- lm(`Diagnosis till death` ~ ., data = data_stand)

vif_values <- vif(linear_model)
vif_values
vif_df <- as.data.frame(vif_values)
str(vif_df)
vif_values <- vif_df$GVIF
column_names <- rownames(vif_df)
vif_values <- vif_df$GVIF
high_vif <- column_names[vif_values > 10]
data_stand_reduced <- data_stand %>% select(-'Original_order', -'ACEIII::ACEIIITotal', -'ACEIII::SubtotalAttention', -'ACEIII::SubtotalMemory', -'ACEIII::SubtotalFluency', -'ACEIII::SubtotalLanguage', -'ACEIII::SubtotalVisuospatial', -'DAD::ExportTotalIadls', -'DAD::ExportTotalDad', -'DAD::ExportTotalBadl', -'Diagnosis_number', -'CBI::PercentBeliefsFCorrected')
m2 <- coxph(
  Surv(`Diagnosis till death`) ~ . + strata(`Sex (Male 1, Female 2)`), 
  data = data_stand_reduced, 
  model = TRUE
)
summary(m2)

m2 <- coxph(Surv(`Diagnosis till death`) ~ . + strata(`Diagnosis_number`) + strata(`Sex (Male 1, Female 2)`) + strata(`CBI::PercentBeliefsFCorrected`) + strata(`CBI::PercentSleepFCorrected`), data = data_stand, model = TRUE)


#summary(m)
```


```{r}
data <- data.frame(
  Variable1 = c(10, 20, 30, 40, 50),
  Variable2 = c(15, 25, 35, 45, 55),
  Variable3 = c(20, 30, 40, 50, 60)
)
data
data_standardized <- scale(data)
data_standardized
```

